# Generated by Django 2.2.5 on 2019-11-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['id'], 'verbose_name': '专业信息', 'verbose_name_plural': '专业信息'},
        ),
    ]
