# Generated by Django 2.2.5 on 2019-11-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('rank', models.CharField(blank=True, max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('special', models.CharField(blank=True, max_length=128)),
                ('belong', models.CharField(max_length=128)),
                ('type1', models.CharField(max_length=128)),
                ('type2', models.CharField(max_length=128)),
            ],
        ),
    ]
