# Generated by Django 2.2.5 on 2019-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191031_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mbti',
            field=models.CharField(default=0, max_length=32),
        ),
    ]
