# Generated by Django 2.2.5 on 2019-10-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='score',
            field=models.CharField(max_length=32),
        ),
    ]
