# Generated by Django 2.2.5 on 2019-10-31 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20191029_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
