# Generated by Django 2.2.5 on 2019-11-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti_type', models.CharField(max_length=32)),
                ('mbti_analysis', models.CharField(max_length=1024)),
            ],
        ),
    ]
