# Generated by Django 2.2.5 on 2019-11-01 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mbtitype',
            options={'ordering': ['mbti_type'], 'verbose_name': 'MBTI信息', 'verbose_name_plural': 'MBTI信息'},
        ),
    ]
