# Generated by Django 2.2.5 on 2019-11-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBTI', '0002_auto_20191101_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbtitype',
            name='id',
        ),
        migrations.AlterField(
            model_name='mbtitype',
            name='mbti_type',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
